add CSS Grid Assignment
IBT-learning/full-stack-software-engineering-2024 pull request #58
Opened 2024-06-02 19:02 UTC by reaapunzell

2024-06-08 03:55 UTC, burrowdown requested changes
I'd like you to take another try at this one, I know you can do it!

2024-06-08 03:55 UTC, burrowdown commented on code/CSS Grid Assignment/style.css
> +    grid-template-columns:4em 10em 1/2fr;
1/2fr isn't a valid measure, if you want a half you can do 0.5fr

2024-06-08 03:55 UTC, burrowdown commented on code/CSS Grid Assignment/style.css
> +    grid-template-rows:
remember not to leave unused properties in!

2024-06-08 03:55 UTC, burrowdown commented on code/CSS Grid Assignment/style.css
> +    width:4em;
In this case, if you want the width to take up the full column, it's not necessary (and actually causes problems) to define the width separately from the grid definition. Best to let the grid handle it.

2024-06-09 21:53 UTC, reaapunzell commented
Hi Danny, 
Thank you for the feedback. I deleted one of your comments by mistake. I did fix the issue before but did not know it would delete it permanently. Apologies. I hope the assignment is better now. Thank you

2024-06-15 06:46 UTC, burrowdown approved these changes
Yes, it looks good now, thank you!

2024-06-15 12:14 UTC, merged